name: axe
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use NodeJS 16.x
      uses: actions/setup-node@v3
      with: 
        node-version: 16.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start & npx await-on http://localhost:3000
    - name: Run Axe
      run: |
        npm install -g @axe-core/cli
        axe http://localhost:3000 --exit