name: Axe Accessibility Tests

on:
  push:
    branches: [main]

jobs:
  axe-test:
    name: Run Axe Accessibility Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        sudo unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies and build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        npm install react-scripts@5.0.1
        npm install typescript@4.x
        npm install --save-dev @typescript-eslint/eslint-plugin@5.59.0 @typescript-eslint/parser@5.59.0
        npm install @testing-library/jest-dom@latest
        npm install --save-dev wait-on
        npm ci
        npm run build --if-present

    - name: Run accessibility tests
      run: |
        npm install -g serve
        serve -s build -l 3000 &
        npx wait-on http://localhost:3000
        npm install -g @axe-core/cli
        axe http://localhost:3000 --exit --chromedriver-path=/usr/local/bin/chromedriver
        kill %1