name: pa11y
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use NodeJS 18.x
      uses: actions/setup-node@v3
      with: 
        node-version: 18.x
    - run: npm install react-scripts@5.0.1
    - run: npm install typescript@4.x
    - run: npm install @typescript-eslint/parser@latest @typescript-eslint/eslint-plugin@latest
    - run: npm install @testing-library/jest-dom@latest
    - run: npm install --save-dev wait-on
    - run: npm ci
    - run: npm run build --if-present
      env:
        NODE_OPTIONS: --openssl-legacy-provider
    - name: Start server and test
      run: |
        npm install -g serve
        npm run build
        serve -s build -l 3000 &
        npx wait-on http://localhost:3000
    - name: Run Axe Pa11y
      run: |
        npm install -g pa11y
        pa11y http://localhost:3000