name: Lighthouse Performance Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse_audit:
    name: Run Lighthouse Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies and build
      env:
        NODE_OPTIONS: '--openssl-legacy-provider'
      run: |
        npm install
        npm install react-scripts@5.0.1
        npm install typescript@4.x
        npm install @typescript-eslint/parser@latest @typescript-eslint/eslint-plugin@latest
        npm install @testing-library/jest-dom@latest
        npm run build

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev google-chrome-stable

    - name: Start test server
      run: |
        npm install -g serve
        serve -s build -l 3000 &
        npx wait-on http://localhost:3000

    - name: Run Lighthouse audit
      run: |
        npm install -g @lhci/cli@0.14.0
        npx lhci autorun
      env:
        LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stop test server
      run: kill $(lsof -t -i:3000)

    - name: Run Lighthouse audit
      run: |
        npm install -g @lhci/cli@0.14.0
        npx lhci autorun --config=./lighthouserc.json
      env:
        LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-report-${{ github.run_id }}
        path: './lighthouse-results'
        retention-days: 7

    - name: Stop test server
      run: kill $(lsof -t -i:3000)